name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:    

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        # with:
        #   fetch-depth: 0
          
      - name: Set up JDK 21
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: 21
          architecture: x64
          cache: 'maven'

      - name: Install Maven dependencies
        run: |
          npx playwright install
          npx playwright@next install
          npx playwright@next install-deps
          
      - name: Build with Maven
        # run: mvn -B clean package -Dmaven.test.skip=true -Dspotless.skip=true --no-transfer-progress
        run: mvn clean install

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run:  |
          mvn -B verify -Dsonar.projectKey=webgoat-sb-kim2 -Dsonar.projectName='webgoat-sb-kim2' \
            -Dsonar.maven.scanAll=true \
            -Dsonar.java.binaries=target/classes \
            -Dsonar.verbose=true \
            org.sonarsource.scanner.maven:sonar-maven-plugin:5.1.0.4751:sonar
